### ISSUE TITLE
AP@recall 40 vs AP@recall 11

### ISSUE THREAD

**Issue by jlqzzz** [Vegeta2020/CIA-SSD#10]
Where should I change the evaluation code to control the evaluation metric ?

**Comment by Vegeta2020** [comment]
In my memory, you may uncommment line 336-340 and comment line 330-334 in CIA-SSD/det3d/datasets/kitti/eval.py.

**Comment by Vegeta2020** [comment]
Sorry, in line 340, "41" should be changed to "40", which complies with the metric. I have commit my changes to fix it, you may uncomment the code if you want to use it.
