### ISSUE TITLE
Don't know which evaluation to use 

### ISSUE THREAD

**Issue by a-akram-98** [Vegeta2020/CIA-SSD#11]
There is two evaluation comes from the **_test.py_**, one comes from these couple of lines:
```
    result_dict, detections = test(data_loader, model, save_dir=None, distributed=distributed)

    for k, v in result_dict["results"].items():
        print(f"Evaluation {k}: {v}")
```

and the other comes from these two lines:

```
        ap_result_str, ap_dict = kitti_evaluate(gt_labels_dir, res_dir, label_split_file=label_split_file, current_class=0,)
        print(ap_result_str)
```

what is the difference between the two and which one did you use in this repo `README.md`

**Comment by Vegeta2020** [comment]
For AP 40 and AP 11 separately.

**Comment by a-akram-98** [comment]
`test()` function gives AP40  ?

**Comment by Vegeta2020** [comment]
I don't remember it now. Just try and compare, the higher is AP40.
