### ISSUE TITLE
Training/Testing environments

### ISSUE THREAD

**Issue by maudzung** [Vegeta2020/CIA-SSD#12]
Hi @Vegeta2020 
Thanks for your work. Could you please give me the library version to reproduce your work here? Such as torch, spconv,...
`pip list` may help me on it. Thanks once again!

**Comment by Vegeta2020** [comment]
Hi @maudzung. We followed Det3D to install the environments, please see the hyper-links of detailed configurations in README file. If you could reproduce Det3D, then you could reproduce our CIA-SSD.

**Comment by maudzung** [comment]
Thanks. Is it restricted to use CUDA v10 and CUDNN v7?
I'm using CUDA v11, CUDNN v8. I could successfully install `spconv v1.0`, `det3d v1.0` with torch v1.3.0. Unfortunately, I have face this error: `/CIA-SSD/det3d/ops/syncbn/syncbn_gpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1011CPUTensorIdEv`. I inspect that this error is related to torch version, but I failed to install spconv v1.0 and det3d (as your instruction) with other torch versions such as torch v1.4 or torch v1.6.

Could you please give me comments on it? Many thanks

**Comment by Vegeta2020** [comment]
Actually, syncbn is a module in Det3D. For your case, I guess you may first have to remove the *.so file & build & *.egg.info in syncbn, then reinstall it with python setup.py build develop. For torch version, I found pytorch version = 1.3 and > 1.3 are okay. When you install torch / spconv / det3d, please ensure installing them under the same cuda and pytorch (for latter two) version. Just for your informatio, I used CUDA 10.0 / 10.1 /11.0 on different servers, but CUDA 10.0 seems cause least problems.

**Comment by maudzung** [comment]
Thank you
