### ISSUE TITLE
IoU Prediction Post Processing

### ISSUE THREAD

**Issue by adpon** [Vegeta2020/CIA-SSD#14]
Hi, I noticed in the code you have a post-processing step for the IoU predictions:

```
iou_preds = (iou_preds.squeeze() + 1) * 0.5
```

I'm wondering why do we add 1 and then multiple by 0.5. I did not notice this step in the paper. Did you find this to work better than using something like a sigmoid function? Thanks.

Reference:
https://github.com/Vegeta2020/CIA-SSD/blob/97ec5dbf4075881cf932bce1558732d0cde82e3f/det3d/models/bbox_heads/mg_head_v4_release.py#L722

**Comment by adpon** [comment]
Ah I understand now sorry. It's because the prediction is always between [-1, 1]

**Comment by xinge008** [comment]
@adpon  How to ensure the prediction is always between [-1, 1]? I saw no activation after IoU branch to regulate the range of output.
