### ISSUE TITLE
The model and loaded state dict do not match exactly

### ISSUE THREAD

**Issue by StevenWang30** [Vegeta2020/CIA-SSD#15]
Thanks for the brilliant work. But I met two questions for training and testing.
1. Can I use the "examples/second/configs/kitti_car_vfev3_spmiddlefhd_rpn1_mghead_syncbn.py" directly? I can run the training in single GPU but cannot achieve the same AP as the pre-trained model.

2. I can run the test.py but I find there is a warning. Is it correct?

```
The model and loaded state dict do not match exactly

unexpected key in source state_dict: bbox_head.tasks.0.conv_iou.bias

these keys have mismatched shape:
+-----------------------------------+----------------------------+----------------------------+
| key                               | expected shape             | loaded shape               |
+-----------------------------------+----------------------------+----------------------------+
| bbox_head.tasks.0.conv_iou.weight | torch.Size([2, 128, 3, 3]) | torch.Size([2, 128, 1, 1]) |
+-----------------------------------+----------------------------+----------------------------+
```

**Comment by Vegeta2020** [comment]
1. Yes, you can use this config file, and you should achieve the similar results.
2. It's about the filter size of the IoU prediction conv head, you may change it (3x3 -> 1x1) in the called mg_head file. The filter size has no much effect on the results.
