### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by SAR-Images-Understanding-Yang** [Vegeta2020/CIA-SSD#17]
How can I solve it!

**Comment by Vegeta2020** [comment]
Could you show more information, e.g., the snapshot of the triggered bug?

**Comment by myrainbowliuying** [comment]
Change all AT_CHECK to TORCH_CHECK

**Comment by yujmo** [comment]
conda install pytorch==1.4.0 torchvision==0.5.0 cudatoolkit=10.1 -c pytorch   亲测有效。

**Comment by shxzhao** [comment]
Thanks for your reply!@Vegeta2020 @myrainbowliuying @yujmo
