### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ywfwyht** [Vegeta2020/CIA-SSD#19]
There is an error in training multi-classes. why?

  File "/home/yht/python_ws/CIA-SSD/det3d/datasets/pipelines/preprocess_v4.py", line 361, in __call__
    gt_dict["gt_boxes"][idx],  # (x, y, z, w, l, h, r)
IndexError: list index out of range

**Comment by Vegeta2020** [comment]
The code is not prepared for multi-class traninig, but it should be easily modified.
