### ISSUE TITLE
The Inference Speed in 3D OD

### ISSUE THREAD

**Issue by hoangduyloc** [Vegeta2020/CIA-SSD#2]
Hello, Thanks for your great work. I have a small wonder hope that you can clarify.
The pipeline of your framework: (a) - Point Cloud, (b) - SPConvNet, (c) - SSFA Module, (e) - Multi-task Head
The average inference time: 30.76 ms (2.84ms for data preprocessing, 24.33ms for Forwardpass, 3.59ms for postprocessing)
As far as my understanding:
- 2.84ms (is the time loading the Lidar PC + voxelization)
- 24.33ms (The time pass though only 2D conv also (c), not include (b) SPConvNet)
- 3.59ms (for NMS to find final predictions)

Could you clarify to me:
1) The total time need to process a frame (load PC + Preprocess + Forwardpass + Postprocess)
2) the time in parts (b)-3D conv, part (c,d,e) - 2D conv. 

I read some papers, they calculate the inference time based on only forwardpass; some based on forwardpass + postprocessing, and some based on preprocessing + forwardpass + postprocessing. I wonder what is the best standard to calculate the inference time.
Thank you so much.

**Comment by Vegeta2020** [comment]
Hi, @hoangduyloc. The inference time is calculated by using the total inference time on the val split to divide the number of samples  (3,769), so you can repeat it by running tools/test.py, and you can either read the auto-calculated results or analyze per-sample time by yourself. So, our inference time corresponds to a complete "load PC + Preprocess + Forwardpass + Postprocess"(as you wrote). Also, we give the forwardpass time as the whole network processing time, we didn't analyze (b)-(e) separately.

**Comment by hoangduyloc** [comment]
@Vegeta2020 
Thanks for clarifying. Have a good day there!
