### ISSUE TITLE
Errors trying to run it as a dockerfile

### ISSUE THREAD

**Issue by dosaidlybro** [Vegeta2020/CIA-SSD#20]
I am trying to run the project on docker and the dockerfile that I built contains the installation steps as mentioned but the moment the execution reaches the line "python setup.py install" it seems to run into a lot of errors....not sure how I am supposed to run it...(I am running it on Ubuntu 21.04)

[ERRORS.odt](https://github.com/Vegeta2020/CIA-SSD/files/6905558/ERRORS.odt)

these are the errors
To elaborate a bit..If you can skip to the line "RUN python setup.py install"...that's where the error messages start popping up.
The errors shown are mostly errors in the .cpp files.

**Comment by Vegeta2020** [comment]
Would you mind to see the [issue](https://github.com/Vegeta2020/SE-SSD/pull/19) first? It may help to solve your problem.
