### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by DiTurr** [Vegeta2020/CIA-SSD#21]
Hi, 
really nice work!! Congrats!! I have a question regarding the inference time. Is the inference time of 30...40 ms also including the voxelization? With such a fine grid, I get voxelization's time of 300 ms or even higher.

**Comment by Vegeta2020** [comment]
The inference time include all the time to process a point cloud sample. The voxelization time should be very minor, and our code follows SECOND and we even fasten it, so 300ms is not reasonable.
