### ISSUE TITLE
The size of voxel

### ISSUE THREAD

**Issue by shxzhao** [Vegeta2020/CIA-SSD#22]
the AP is so low when I change the voxel size to [0.1, 0.1, 0.1]. Can you give me some advice?@Vegeta2020
bbox AP:9.09, 9.09, 9.09
bev  AP:9.09, 9.09, 9.09
3d   AP:9.09, 9.09, 9.09
aos  AP:9.09, 9.07, 9.07
car AP(Average Precision)@0.70, 0.50, 0.50:
bbox AP:9.09, 9.09, 9.09
bev  AP:9.09, 9.09, 9.09
3d   AP:9.09, 9.09, 9.09
aos  AP:9.09, 9.07, 9.07

**Comment by Vegeta2020** [comment]
Hi @shxzhao Have you also checked other configures carefully, e.g., the target assigner, the feature map sizes, and post processing?

**Comment by shxzhao** [comment]
Tnanks for your reply! I'll check it again。
