### ISSUE TITLE
Inference queries 

### ISSUE THREAD

**Issue by abhigoku10** [Vegeta2020/CIA-SSD#24]
@Vegeta2020  thanks for opensourcing the code base , please find the below queries 
1. I am nto able to setup spconv in windows can we replace the packages  with sparseconvnet from facebook 
2. can we run inference on the cpu ?

THanks in advance

**Comment by Vegeta2020** [comment]
Hi @abhigoku10 For your queries
1. There are more optimzation in spconv than sparseconvnet, but I have not tried sparseconvnet yet.
2. Yes, you may cancel all ".cuda" operations to avoid to run on the gpu.
