### ISSUE TITLE
Tons of incorrect detections when testing on my own dataset

### ISSUE THREAD

**Issue by DavidWZX** [Vegeta2020/CIA-SSD#25]
Hi @Vegeta2020  ! Thanks for sharing your work here, and I have already reproduced on KITTI testing dataset. The results of 3d_bboxes are clearly close to the profile of objects.
But when I replaced the  .bin files in /testing/velodyne/ with my own dataset, created data and run test code, it gave me tons of messy results which are obviously wrong ( It may be right if it was recorded in a cars junkyard, but sadly it was not).
So have you and your team tested on you own dataset before? It will be very helpful if you can share the instruction on how to test on our own dataset. And thanks for you patience.

**Comment by Vegeta2020** [comment]
Hi, @DavidWZX If you want to test the CIA-SSD model on your own dataset, I suggest you pay more attention to the data format of KITTI dataset, and you should keep your data format same as it, e.g., coordinate system is very important, so you may find the KITTI paper to figure it out. Also, the data distribution may affect the detection performance, e.g., the number of layser beams or valid covering range may affect the point distribution, but these factors should not significantly decrease the detection precision. Good luck!
