### ISSUE TITLE
Data sampling questions

### ISSUE THREAD

**Issue by sjg918** [Vegeta2020/CIA-SSD#26]
HI. Thank you for your work. (SE-SSD is also grateful.)

There is data sampling codes available at https://github.com/Vegeta2020/CIA-SSD/blob/master/det3d/core/sampler/sample_ops_v2.py but it didn't help for me. (TOO DIFFICULT for me!)
And the content of the paper "SECOND: Sparsely Embedded Convolutional Detection" didn't help me either.

How do you determine the center position of a sampled object? Do you just use the center position of the bounding box?
How many sample ground truths from the database do you use for one batch?
What strategies do you use to check for collisions in sample:
ex 1) IoU 0.05
ex 2) Distance 1m <
What about the existing points at the sampled object's location? Remove all existing points that were inside the bounding box? 

thx.

**Comment by Vegeta2020** [comment]
Hi @sjg918. The code is actually not so hard to understand, but it may take some time to read. For you questions, the center position is kept as in the original scenes; all dimensions of the sampled box are used; you may find the number of sampled boxes in the config file; the collision test is based on the calculation of BEV IoU ( with a very small threshold) and the overlapped box would be filtered;  existing points in the sampled boxes will be removed. Actually, all your questions could be easily addressed if you take some time to read the code, hope you good luck :)

**Comment by sjg918** [comment]
Thank you. Have a nice day. ^^)b
