### ISSUE TITLE
load pretrained model error

### ISSUE THREAD

**Issue by nicholaswhf** [Vegeta2020/CIA-SSD#28]
help!
When I load the pretrained model, got the following errors

`these keys have mismatched shape:
+-----------------------------------+-------------------------------+-------------------------------+
| key                               | expected shape                | loaded shape                  |
+-----------------------------------+-------------------------------+-------------------------------+
| backbone.middle_conv.0.weight     | torch.Size([16, 3, 3, 3, 4])  | torch.Size([3, 3, 3, 4, 16])  |
| backbone.middle_conv.3.weight     | torch.Size([16, 3, 3, 3, 16]) | torch.Size([3, 3, 3, 16, 16]) |
| backbone.middle_conv.6.weight     | torch.Size([32, 3, 3, 3, 16]) | torch.Size([3, 3, 3, 16, 32]) |
| backbone.middle_conv.9.weight     | torch.Size([32, 3, 3, 3, 32]) | torch.Size([3, 3, 3, 32, 32]) |
| backbone.middle_conv.12.weight    | torch.Size([32, 3, 3, 3, 32]) | torch.Size([3, 3, 3, 32, 32]) |
| backbone.middle_conv.15.weight    | torch.Size([64, 3, 3, 3, 32]) | torch.Size([3, 3, 3, 32, 64]) |
| backbone.middle_conv.18.weight    | torch.Size([64, 3, 3, 3, 64]) | torch.Size([3, 3, 3, 64, 64]) |
| backbone.middle_conv.21.weight    | torch.Size([64, 3, 3, 3, 64]) | torch.Size([3, 3, 3, 64, 64]) |
| backbone.middle_conv.24.weight    | torch.Size([64, 3, 3, 3, 64]) | torch.Size([3, 3, 3, 64, 64]) |
| backbone.middle_conv.27.weight    | torch.Size([64, 3, 3, 3, 64]) | torch.Size([3, 3, 3, 64, 64]) |
| backbone.middle_conv.30.weight    | torch.Size([64, 3, 3, 3, 64]) | torch.Size([3, 3, 3, 64, 64]) |
| backbone.middle_conv.33.weight    | torch.Size([64, 3, 3, 3, 64]) | torch.Size([3, 3, 3, 64, 64]) |
| backbone.middle_conv.36.weight    | torch.Size([64, 3, 3, 3, 64]) | torch.Size([3, 3, 3, 64, 64]) |
| backbone.middle_conv.39.weight    | torch.Size([64, 3, 1, 1, 64]) | torch.Size([3, 1, 1, 64, 64]) |
| bbox_head.tasks.0.conv_iou.weight | torch.Size([2, 128, 3, 3])    | torch.Size([2, 128, 1, 1])    |
+-----------------------------------+-------------------------------+-------------------------------+
`

**Comment by nicholaswhf** [comment]
I moderate the checkpoint.py
![image](https://user-images.githubusercontent.com/28783563/159107729-f95ad183-d19d-4e83-875d-e68faf75023a.png)
and it works.
But i got a low AP.
![image](https://user-images.githubusercontent.com/28783563/159107763-fb0be36f-060f-42b0-a19a-365a95d7dafc.png)
![image](https://user-images.githubusercontent.com/28783563/159107777-4119cebe-9ccd-4689-8bb8-e2c15a3b893d.png)

**Comment by Vegeta2020** [comment]
@nicholaswhf Hi, did you use the right config file "kitti_car_vfev3_spmiddlefhd_rpn1_mghead_syncbn.py"? The change of checkpoint is not recommended, you may change the weight shape of the network at least.

**Comment by jiangliangliang2020** [comment]
@Vegeta2020 你好，我想请问一下配置环境是什么？我使用torch1.6版本，det3d编译不成功，使用torch1.4，编译成功，但是运行train.py会报错缺少libtorch_cpu.so等文件

**Comment by jiangliangliang2020** [comment]
@Vegeta2020 你好，我复现了你的代码，然后出现了两个结果，请问是什么原因？

![2022-04-08 15-28-04屏幕截图](https://user-images.githubusercontent.com/73384996/162649934-c321e739-0648-463f-8236-fd373053b675.png)

**Comment by nicholaswhf** [comment]
这是两个评价标准，上面的是AP R11，下面的是AP R40，分别表示绘制PR曲线后估算AP值时使用11插值点与40插值点。

**Comment by jiangliangliang2020** [comment]
@nicholaswhf 谢谢你的回复，我知道了，他原论文用的是AP R40吗？

**Comment by jiangliangliang2020** [comment]
@nicholaswhf 谢谢你的回复，我知道了，他原论文用的是AP R40吗？

**Comment by nicholaswhf** [comment]
具体您可以看作者的论文。通常而言，在文章中如果与其他算法进行比较的时候，倾向于使用AP R11，这是因为最开始KITTI官方使用的就只有R11这一种，现在官方也逐渐开始使用R40了。

**Comment by jiangliangliang2020** [comment]
好的，我知道了，非常感谢

**Comment by nicholaswhf** [comment]
My pleasure.
