### ISSUE TITLE
Clarification on parameter choices

### ISSUE THREAD

**Issue by SchDevel** [Vegeta2020/CIA-SSD#3]
Hey,

thanks for the great work.

Just for clarification, I have one small question, that came up, when looking at the _kitti_car_vfev3_spmiddlefhd_rpn1_mghead_syncbn.py_ file.
How did you choose your parameters for testing (e.g. nms_pre_max_size=1000, nms_post_max_size=100, nms_iou_threshold=0.01, score_threshold=0.3)?

Is the assumption right, that they heavily influence your AP values on the validation and also on the KITTI test split?
If so, did you use the provided values for the KITTI submission?

Best regards

SchDevel

**Comment by Vegeta2020** [comment]
Hi, @SchDevel . We didn't do experiments on these paremeters, and we use the default ones on both val and test splits. I guess it may produce better results if you try to refine them carefully, but it's not the task of this work.
