### ISSUE TITLE
the gtboxes

### ISSUE THREAD

**Issue by nicholaswhf** [Vegeta2020/CIA-SSD#30]
Hello, may I ask if the gt boxes are converted from camera to lidar, because I found that there is a bias after visualization.
![image](https://user-images.githubusercontent.com/28783563/162563977-e2132430-c0c6-4020-8940-0665af9bbb94.png)

**Comment by gc625** [comment]
maybe the yaw angle is inverted?

**Comment by nicholaswhf** [comment]
Thank gc625 for reply. Emmmmm, can you tell me how to solve it?🥲

**Comment by nicholaswhf** [comment]
我找到原因了，是我在可视化的时候把lwh三个顺序搞错了。
I debugged the error, I made the order of lwh when visualizing.
