### ISSUE TITLE
where is the  Distance-variant IoU-weighted NMS code

### ISSUE THREAD

**Issue by vvincenttttt** [Vegeta2020/CIA-SSD#31]
Hi,
nice repo!

I wonder to know where is the  Distance-variant IoU-weighted NMS code?

thanks!

**Comment by Vegeta2020** [comment]
@TianhaoFu Please find it at [here](https://github.com/Vegeta2020/CIA-SSD/blob/master/det3d/core/bbox/box_torch_ops.py#L550).
