### ISSUE TITLE
val时指标全是0

### ISSUE THREAD

**Issue by u1095279221321** [Vegeta2020/CIA-SSD#4]
我们在使用官方的配置文件训练，val时指标全是0，不知道是否是我们训练有问题，能否提供一下权重

**Comment by Vegeta2020** [comment]
@u1095279221321 我在Readme中"here"处提供了预训练模型链接，你看是否能够下载：
![image](https://user-images.githubusercontent.com/75373109/105122591-7296f700-5b11-11eb-800a-683bd58d4f51.png)

**Comment by u1095279221321** [comment]
很感谢您的回复，我们在运行test_v3.py得到这样一个错误，AttributeError: 'ConfigDict' object has no attribute 'far_points_first'。在配置文件中使用("val", 1)，可以运行，但结果全是０，不知道哪里有问题。非常感谢。

**Comment by Vegeta2020** [comment]
@u1095279221321 test_v3.py是在test set测试的代码（参看第131行代码），test.py是在val set上测试的代码。“far_points_first”缺失，需要确保你使用的config文件有kitti_car_vfev3_spmiddlefhd_rpn1_mghead_syncbn.py中18行-32行的参数，不过这些参数对于性能提升是没有作用的。

**Comment by u1095279221321** [comment]
我们使用kitti_car_vfev3_spmiddlefhd_rpn1_mghead_syncbn.py和cia-ssd-model.pth进行测试，得到下面的错误
１、The model and loaded state dict do not match exactly
unexpected key in source state_dict: bbox_head.tasks.0.conv_iou.bias
these keys have mismatched shape:
+-----------------------------------+----------------------------+----------------------------+
| key                               | expected shape             | loaded shape               |
+-----------------------------------+----------------------------+----------------------------+
| bbox_head.tasks.0.conv_iou.weight | torch.Size([2, 128, 3, 3]) | torch.Size([2, 128, 1, 1]) |
+-----------------------------------+----------------------------+----------------------------+
这个错误,是最后的输出不匹配，在配置文件中我们没有找到怎么配置
２、/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
这个错误好像是标签溢出，我们改用三个类别的配置文件，就没有这个问题了，请问这个问题在训练单类别时如何避免

感谢您的回复

**Comment by u1095279221321** [comment]
我们删去了mg_head_v4_release.py中的752-758行，问题中就没有了，现在以及可以测试，非常感谢。还有一个问题
在ｔｅｓｔ中
　　# todo: this evaluation is different from previous one
        ap_result_str, ap_dict = kitti_evaluate(gt_labels_dir, res_dir, label_split_file=label_split_file, current_class=0,)
这个指标与上边的指标有什么不同嘛，这两个指标哪一个更官方一些，我们发现下边的这个指标更高一些。

**Comment by Vegeta2020** [comment]
@u1095279221321  我们在运行代码时，没有出现752-758行导致的问题。两个指标AP11和AP40都是官方指标，可以参看KITTI官网说明。
