### ISSUE TITLE
Question about label assign in CIA-SSD

### ISSUE THREAD

**Issue by GaryLIA** [Vegeta2020/CIA-SSD#5]
I read the code in trainer.py. I found that the label of each anchor had already given in the value of data_batch. I want to know where is the code of labeling the anchors and when it runs.

**Comment by CUHKWilliam** [comment]
Hi @GaryLIA ! The code of labeling the anchors lies in the function "create_target_np" in "det3d/core/anchor/target_ops.py". The code will be invoked when "det3d/datasets/pipelines/preprocess_v4.py: 351" is executed during dataloader iteration.
