### ISSUE TITLE
No CUDA runtime is found, using CUDA_HOME='/usr'

### ISSUE THREAD

**Issue by sentinel3** [Vegeta2020/CIA-SSD#6]
Hi I face the above error when try :
`python setup.py install`

with the following environment within `anaconda`:
```
OS: Ubuntu 18.04
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
pytorch : v 1.7.1 
```
what relied environment needed to run your repo? thx.

**Comment by Vegeta2020** [comment]
Hi @sentinel3 , our codebase is based on Det3D, so you may find the env with the link https://github.com/poodarchu/Det3D/blob/master/INSTALLATION.md.
For your case, I guess you should config the environment variable "CUDA_HOME" with your cuda path, such as "export CUDA_HOME=/usr/local/cuda-10.1".
