### ISSUE TITLE
Get the iou3d in KITTI dataset

### ISSUE THREAD

**Issue by a-akram-98** [Vegeta2020/CIA-SSD#7]
the KITTI dataset gives computeBox3D.m to help to extract the labels from the label.txt and here is a part of the code

```
l = object.l;
w = object.w;
h = object.h;

% 3D bounding box corners
x_corners = [l/2, l/2, -l/2, -l/2, l/2, l/2, -l/2, -l/2];
y_corners = [0,0,0,0,-h,-h,-h,-h];
z_corners = [w/2, -w/2, -w/2, w/2, w/2, -w/2, -w/2, w/2];
```

so from the previous code it appears that the dimension that gets the x component is l and for y is h, and for z is w, but in the iou3d_utils.py in function boxes_iou3d_cpu in the function description the expected in put is like this

    """
    Input (torch):
        boxes_a: (N, 7) [x, y, z, h, w, l, ry], torch tensor with type float32
        boxes_b: (M, 7) [x, y, z, h, w, l, ry], torch tensor with type float32
        rect: True/False means boxes in camera/velodyne coord system.
    Output:
        iou_3d: (N, M)
    """
I'm using labels in rect coordinates, so what is the order of the input I must use, I'm really confused.

**Comment by Vegeta2020** [comment]
@a-akram-98 The iou3d module is borrowed from a previous work (seems PointRCNN) with much modificatins and comments from me, it's a long time ago, now I'm only sure the function "boxes_aligned_iou3d_gpu" is correct because I tested it when I called it in IoU prediction. For your question, you can see that I set a parameter "box_mode" in the function "boxes_iou3d_cpu" with default value "wlh", so you only need to set a correct box_mode to correspond to your input dimesions, and the program will parse the box value correctly. Therefore, you may ignore my comments there, but please do more check on the code.

**Comment by a-akram-98** [comment]
@Vegeta2020 Thanks I will, another question please I tried to modify the network so that the out put from `FFSA` (or the input to the `MultiGroupHead` ) become less than `(batch_size,128,200,176)`  maybe something like `(batch_size,128,27,20)` but it gives me error due to dimensional mismatch, as apparently the ground truth labels came in shape `(batch_size,70400) `, can you tell me please why is every sample has 70,400 label and bounding boxes, as it confesses me.

**Comment by a-akram-98** [comment]
@Vegeta2020 and if you can tell me how to change the size of ground truth labels which is `70400` to match the new dimensions.

**Comment by Vegeta2020** [comment]
> @Vegeta2020 Thanks I will, another question please I tried to modify the network so that the out put from `FFSA` (or the input to the `MultiGroupHead` ) become less than `(batch_size,128,200,176)` maybe something like `(batch_size,128,27,20)` but it gives me error due to dimensional mismatch, as apparently the ground truth labels came in shape `(batch_size,70400) `, can you tell me please why is every sample has 70,400 label and bounding boxes, as it confesses me.

70400=200*176*2, in which 200 and 176 correspond to feature map size, and 2 means number of anchors on each location.

**Comment by Vegeta2020** [comment]
> @Vegeta2020 and if you can tell me how to change the size of ground truth labels which is `70400` to match the new dimensions.

Both .reshape() or view() are okay.

**Comment by a-akram-98** [comment]
> > @Vegeta2020 Thanks I will, another question please I tried to modify the network so that the out put from `FFSA` (or the input to the `MultiGroupHead` ) become less than `(batch_size,128,200,176)` maybe something like `(batch_size,128,27,20)` but it gives me error due to dimensional mismatch, as apparently the ground truth labels came in shape `(batch_size,70400) `, can you tell me please why is every sample has 70,400 label and bounding boxes, as it confesses me.
> 
> 70400=200_176_2, in which 200 and 176 correspond to feature map size, and 2 means number of anchors on each location.

@Vegeta2020  Okay but, if I down sampled the feature map to anything less than `200*176` it will give dimension mismatch due to that the ground truth is already 70400, so I need to reduce the number of ground truth `(anchors, I think, as this part still vague to me, why the ground truth labels of size 70400)` but I don't know which parameters in data generation is responsible for giving `70400` ground truth label for each sample

**Comment by a-akram-98** [comment]
> > @Vegeta2020 and if you can tell me how to change the size of ground truth labels which is `70400` to match the new dimensions.
> 
> Both .reshape() or view() are okay.

@Vegeta2020 I need to reduce it not changing its shape.

**Comment by Vegeta2020** [comment]
> > > @Vegeta2020 Thanks I will, another question please I tried to modify the network so that the out put from `FFSA` (or the input to the `MultiGroupHead` ) become less than `(batch_size,128,200,176)` maybe something like `(batch_size,128,27,20)` but it gives me error due to dimensional mismatch, as apparently the ground truth labels came in shape `(batch_size,70400) `, can you tell me please why is every sample has 70,400 label and bounding boxes, as it confesses me.
> > 
> > 
> > 70400=200_176_2, in which 200 and 176 correspond to feature map size, and 2 means number of anchors on each location.
> 
> @Vegeta2020 Okay but, if I down sampled the feature map to anything less than `200*176` it will give dimension mismatch due to that the ground truth is already 70400, so I need to reduce the number of ground truth `(anchors, I think, as this part still vague to me, why the ground truth labels of size 70400)` but I don't know which parameters in data generation is responsible for giving `70400` ground truth label for each sample

See the called functions in target_assigner in the preprocess_v4.py, you may find it.

**Comment by a-akram-98** [comment]
> > > > @Vegeta2020 Thanks I will, another question please I tried to modify the network so that the out put from `FFSA` (or the input to the `MultiGroupHead` ) become less than `(batch_size,128,200,176)` maybe something like `(batch_size,128,27,20)` but it gives me error due to dimensional mismatch, as apparently the ground truth labels came in shape `(batch_size,70400) `, can you tell me please why is every sample has 70,400 label and bounding boxes, as it confesses me.
> > > 
> > > 
> > > 70400=200_176_2, in which 200 and 176 correspond to feature map size, and 2 means number of anchors on each location.
> > 
> > 
> > @Vegeta2020 Okay but, if I down sampled the feature map to anything less than `200*176` it will give dimension mismatch due to that the ground truth is already 70400, so I need to reduce the number of ground truth `(anchors, I think, as this part still vague to me, why the ground truth labels of size 70400)` but I don't know which parameters in data generation is responsible for giving `70400` ground truth label for each sample
> 
> See the called functions in target_assigner in the preprocess_v4.py, you may find it.

@Vegeta2020  Thank you very much, that's really helped me a lot
