### ISSUE TITLE
multi class prediction->all_vfev3:two errors occur

### ISSUE THREAD

**Issue by vehxianfish** [Vegeta2020/CIA-SSD#9]
Hello, Thanks for your great work!
all errors occur  on command `run python test.py`
1. kitti_all_vfev3_spmiddlefhd_rpn1_mghead_syncbn.py:
    `AttributeError: 'ConfigDict' object has no attribute 'far_points_first'`
2. make up in all_vfev3 file and on dict:  `voxel_generator`
     `
    voxel_generator = dict(
    range=[0, -40.0, -3.0, 70.4, 40.0, 1.0],
    voxel_size=[0.05, 0.05, 0.1],
    max_points_in_voxel=5,
    max_voxel_num=40000,
    far_points_first = False
    `
  another ** error occurs**:
  `KeyError: 'RPN is not in the neck registry'`
3. replace "RPN" to "SSFA",program can run,but speed is lower.  

so question is:
1. are these error's reasion is my  operation or the kitti_all_vfev3_spmiddlefhd_rpn1_mghead_syncbn.py file have fault
2. Do you test all class  test eg "car\cyclist\people" or how to speed up for multi-class prediction
thank you for your wonderful work!

**Comment by Vegeta2020** [comment]
Hi, @vehxianfish I didn't try kitti_all_vfev3_spmiddlefhd_rpn1_mghead_syncbn.py. As shown in the paper, I only tested our model on the car dataset, while I have tested it and it could also be run on the server. Please notice all parameters (including "far_points_first") in "my_paras" in the car_config, and you can copy all related paras to the all_config to fix the bugs. For the speed, please ensure modifying the code for all class object detection based on my preprocess_v4.py, as the default version preprocess.py is inefficient, you may find all details when you check it.

**Comment by vehxianfish** [comment]
Thanks for your reply,@Vegeta2020.I will try it later.thank you again.

**Comment by a-akram-98** [comment]
@vehxianfish if you trained it successfully, please tell me what did you do ?

**Comment by vehxianfish** [comment]
@a-akram-98 .my operation like top review.but I am not train dataset.I only test.py based on model trained one class.
Do you have specific error or issue posed here?

**Comment by vehxianfish** [comment]
@Vegeta2020 Hi,thank you for your best work and quickly reply.
I have trained test more than 5s.But I can't reproduce the precision.
if there I have errors on training,like,trainning more epochs,parameters modified etc.
my config is
```
4*GPUS--20800Ti
torch==1.4.0  
spconv==1.2.1  
```


and one trainning results as follows:
```Evaluation official: car AP(Average Precision)@0.70, 0.70, 0.70:
bbox AP:90.58, 79.25, 77.96
bev  AP:90.27, 87.64, 79.86
3d   AP:86.70, 69.46, 67.07
aos  AP:90.47, 79.00, 77.53
car AP(Average Precision)@0.70, 0.50, 0.50:
bbox AP:90.58, 79.25, 77.96
bev  AP:98.82, 89.73, 89.12
3d   AP:90.59, 79.83, 78.87
aos  AP:90.47, 79.00, 77.53


Car AP@0.70, 0.70, 0.70:
bbox AP:96.2676, 79.8400, 76.8224
bev  AP:96.0712, 89.3099, 84.6281
3d   AP:87.1592, 70.5361, 65.4615
aos  AP:96.12, 79.58, 76.40
Car AP@0.70, 0.50, 0.50:
bbox AP:96.2676, 79.8400, 76.8224
bev  AP:99.4537, 95.4731, 90.7296
3d   AP:96.4732, 84.1966, 79.4530
aos  AP:96.12, 79.58, 76.40```

**Comment by a-akram-98** [comment]
> @Vegeta2020 Hi,thank you for your best work and quickly reply.
> I have trained test more than 5s.But I can't reproduce the precision.
> if there I have errors on training,like,trainning more epochs,parameters modified etc.
> my config is
> 
> ```
> 4*GPUS--20800Ti
> torch==1.4.0  
> spconv==1.2.1  
> ```
> 
> and one trainning results as follows:
> 
> ```
> bbox AP:90.58, 79.25, 77.96
> bev  AP:90.27, 87.64, 79.86
> 3d   AP:86.70, 69.46, 67.07
> aos  AP:90.47, 79.00, 77.53
> car AP(Average Precision)@0.70, 0.50, 0.50:
> bbox AP:90.58, 79.25, 77.96
> bev  AP:98.82, 89.73, 89.12
> 3d   AP:90.59, 79.83, 78.87
> aos  AP:90.47, 79.00, 77.53
> 
> 
> Car AP@0.70, 0.70, 0.70:
> bbox AP:96.2676, 79.8400, 76.8224
> bev  AP:96.0712, 89.3099, 84.6281
> 3d   AP:87.1592, 70.5361, 65.4615
> aos  AP:96.12, 79.58, 76.40
> Car AP@0.70, 0.50, 0.50:
> bbox AP:96.2676, 79.8400, 76.8224
> bev  AP:99.4537, 95.4731, 90.7296
> 3d   AP:96.4732, 84.1966, 79.4530
> aos  AP:96.12, 79.58, 76.40```
> ```

If you can help, I'm little confused from the output of `AP` there are two kinds of `AP` what is the difference between the two outputs 
and en each Evaluation technique, There is two outputs One is after `0.7 0.7 0.7`
and the other other is after `0.7 0.5 0.5 `what is the difference between those two

**Comment by vehxianfish** [comment]
> > @Vegeta2020 Hi,thank you for your best work and quickly reply.
> > I have trained test more than 5s.But I can't reproduce the precision.
> > if there I have errors on training,like,trainning more epochs,parameters modified etc.
> > my config is
> > ```
> > 4*GPUS--20800Ti
> > torch==1.4.0  
> > spconv==1.2.1  
> > ```
> > 
> > 
> > and one trainning results as follows:
> > ```
> > bbox AP:90.58, 79.25, 77.96
> > bev  AP:90.27, 87.64, 79.86
> > 3d   AP:86.70, 69.46, 67.07
> > aos  AP:90.47, 79.00, 77.53
> > car AP(Average Precision)@0.70, 0.50, 0.50:
> > bbox AP:90.58, 79.25, 77.96
> > bev  AP:98.82, 89.73, 89.12
> > 3d   AP:90.59, 79.83, 78.87
> > aos  AP:90.47, 79.00, 77.53
> > 
> > 
> > Car AP@0.70, 0.70, 0.70:
> > bbox AP:96.2676, 79.8400, 76.8224
> > bev  AP:96.0712, 89.3099, 84.6281
> > 3d   AP:87.1592, 70.5361, 65.4615
> > aos  AP:96.12, 79.58, 76.40
> > Car AP@0.70, 0.50, 0.50:
> > bbox AP:96.2676, 79.8400, 76.8224
> > bev  AP:99.4537, 95.4731, 90.7296
> > 3d   AP:96.4732, 84.1966, 79.4530
> > aos  AP:96.12, 79.58, 76.40```
> > ```
> 
> If you can help, I'm little confused from the output of `AP` there are two kinds of `AP` what is the difference between the two outputs
> and en each Evaluation technique, There is two outputs One is after `0.7 0.7 0.7`
> and the other other is after `0.7 0.5 0.5 `what is the difference between those two

Hi,In my opinion.It is a threshold for IOU to filter rect.
But I dont' konw the differencen between Car Evaluation official: car AP(Average Precision) and Car AP@.
If you know,can you tell me?
Do you reproduce the AP training from scratch?

**Comment by a-akram-98** [comment]
Nope, I don't really know that's why I'm asking, and yeah I reproduced the training AP `(Car mode not All mode)` from the scratch.
@Vegeta2020 Can you please tell us what is the differences between all these AP outputs

**Comment by vehxianfish** [comment]
@a-akram-98 .emmmm.Do you trainning by yourself,not use pre-trained weights?
But I can't reproduce it.
Can you tell me your trainning step or modify something?
thank you! can you pose your result picture in here?

**Comment by Vegeta2020** [comment]
Hi @vehxianfish @a-akram-98, 0.5 and 0.7 mean IoU threshold, and the three columns mean easy, moderate, and hard difficulty levels, respectively.

**Comment by a-akram-98** [comment]
> Hi @vehxianfish @a-akram-98, 0.5 and 0.7 mean IoU threshold, and the three columns mean easy, moderate, and hard difficulty levels, respectively.

@Vegeta2020 Yes but there ia more than output for AP what each one correspondence?

**Comment by a-akram-98** [comment]
> @a-akram-98 .emmmm.Do you trainning by yourself,not use pre-trained weights?
> But I can't reproduce it.
> Can you tell me your trainning step or modify something?
> thank you! can you pose your result picture in here?

@vehxianfish Iwill pose my results soon , and yes I loaded the pretrained model and it worked and I trained it from scratch with the default hyperparameters and also worked

I didn't train it on multi GPUs, but just ine GPU, You can try train it on just only one GPU.

**Comment by vehxianfish** [comment]
thank you very much.

**Comment by vehxianfish** [comment]
@a-akram-98 .thank you very much for you!

**Comment by vehxianfish** [comment]
@a-akram-98 .Hi,can you pose your lib version on here.eg:spconv,pytorch and so on.emmm,Can you also pose your result here and parameters if modified? thank you very much! I can't reproduce result.thank you~

**Comment by vehxianfish** [comment]
@Vegeta2020 .Thank you for your great work and replay for me.Can you describe your lib version.eg:spconv,pytorcn and so on. I doubt version of lib can impact the result in some way.
